### ISSUE TITLE
Tuple of Tuples or Tuple of List

### ISSUE THREAD

**Issue by chandralegend** [Jaseci-Labs/jaclang#220]
For example

```python
x = {"a": "apple", "b": "banana"};
((a, apple), (b, banana)) = x.items(); # a = "a", apple="apple" and so on.
```

Error
```bash
Traceback (most recent call last):
  File "/opt/conda/envs/lame-tool/bin/jac", line 8, in <module>
    sys.exit(start_cli())
             ^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/cli/cli.py", line 138, in start_cli
    ret = command.call(**args_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/cli/cmdreg.py", line 40, in call
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/cli/cli.py", line 52, in run
    __jac_import__(
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/importer.py", line 52, in jac_import
    if error := transpile_jac(full_target):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/transpiler.py", line 20, in transpile_jac
    print_pass = PyOutPass(input_ir=code.ir, prior=code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/ir_pass.py", line 17, in __init__
    Transform.__init__(self, input_ir, prior)
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/transform.py", line 45, in __init__
    self.ir = self.transform(ir=input_ir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/ir_pass.py", line 89, in transform
    self.traverse(ir)
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/ir_pass.py", line 98, in traverse
    self.enter_node(node)
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/ir_pass.py", line 30, in enter_node
    getattr(self, f"enter_{pascal_to_snake(type(node).__name__)}")(node)
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/main/pyout_pass.py", line 47, in enter_module
    self.compile_bytecode(mod, mod_path=mod_path, out_path=out_path_pyc)
  File "/opt/conda/envs/lame-tool/lib/python3.11/site-packages/jaclang/compiler/passes/main/pyout_pass.py", line 62, in compile_bytecode
    codeobj = compile(source=node.gen.py_ast, filename=mod_path, mode="exec")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expression must have Store context but has Load instead
```

**Comment by marsninja** [comment]
Fixed by [aa11d51](https://github.com/Jaseci-Labs/jaclang/commit/aa11d51ac3602d4949c068267f3fceade325d2cf)
